# Generated by Django 6.0.5 on 2026-05-12 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('student_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=257)),
                ('enrollment_year', models.DateTimeField(verbose_name='Enrollement year')),
                ('birth_year', models.DateTimeField(verbose_name='Birth year')),
            ],
        ),
    ]
